// fetching data from google sheet
export async function getFamilyData() {
  const response = await fetch(
    "https://api.sheetbest.com/sheets/e10ee71f-989d-4967-82c2-cc67aa158665"
  );
  const data = await response.json();

  return data.map((person) => ({
    // IDs
    id: person["رقم"],
    pid: person["رمز الاب"] || person["رمز الزوج"],
    // info
    name: person["الاسم"],
    birth: person["ميلاد"],
    death: person["وفات"],
    gender: person["الجنس"],
    img: person["صورة"] || null,
    // related
    father: person["الاب"],
    mother: person["الام"],
    Marriages: person["زوج"],
    childrenNumber: person["عدد الأبناء"],
    lactatingMother: person["الأم رضاع"],
    fosterFather: person["الأب رضاع"],
    fosterSiblings: person["إخوة رضاع"],
    // contact
    cantact: person["تواصل"],
    tags: [
      person["رمز الزوج"].trim() !== "" ? "assistant" : null,
      person["الجنس"] === "أنثى" ? "female" : null,
    ],
    lifeStatus: person["وفات"] ? "متوفى" : null,
  }));
}

// export const database = [
//   {
//     id: 0,
//     name: "حمد عبد الله الجبر",
//     gender: "ذكر",
//     age: 0,
//     alive: false,
//     // img: "https://cdn.balkan.app/shared/2.jpg",
//     tags: ["dead"],
//     feild_1: "dead",
//     img_1: "./assets/grave.png",
//   },
//   {
//     id: 1,
//     pid: 0,
//     tags: ["assistant", "wife", "female"],
//     name: "منيرة السبيعي",
//     gender: "أنثى",
//     age: 0,
//     alive: false,
//     // img: "https://cdn.balkan.app/shared/9.jpg",
//   },
//   {
//     id: 2,
//     pid: 1,
//     tags: ["female"],
//     name: "عائشة",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "assets/عبد الله الجبر.jpg",
//   },
//   {
//     id: 3,
//     pid: 1,
//     name: "عبد الله",
//     gender: "ذكر",
//     age: 73,
//     alive: true,
//     img: "assets/عبد الله الجبر.jpg",
//   },
//   {
//     id: 4,
//     pid: 3,
//     tags: ["assistant", "wife"],
//     name: "حصة محمد العميل",
//     gender: "أنثى",
//     age: 53,
//     alive: true,
//     // img: "https://cdn.balkan.app/shared/9.jpg",
//   },
//   {
//     id: 5,
//     pid: 4,
//     name: "منيرة",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "https://cdn.balkan.app/shared/4.jpg",
//   },
//   {
//     id: 6,
//     pid: 4,
//     name: "أسماء",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "https://cdn.balkan.app/shared/5.jpg",
//   },
//   {
//     id: 7,
//     pid: 4,
//     name: "حمد",
//     gender: "ذكر",
//     age: 0,
//     alive: true,
//     img: "assets/حمد عبد الله.jpg",
//   },
//   {
//     id: 8,
//     pid: 4,
//     name: "محمد",
//     gender: "ذكر",
//     age: 0,
//     alive: true,
//     img: "assets/محمد عبد الله.jpg",
//   },
//   {
//     id: 9,
//     pid: 3,
//     tags: ["assistant"],
//     name: "هدى أحمد القرزعي",
//     gender: "أنثى",
//     age: 73,
//     alive: true,
//     // img: "https://cdn.balkan.app/shared/9.jpg",
//   },
//   {
//     id: 10,
//     pid: 4,
//     name: "عبد الرحمن",
//     gender: "ذكر",
//     age: 0,
//     alive: true,
//     img: "assets/عبد الرحمن عبد الله.jpg",
//   },
//   {
//     id: 11,
//     pid: 4,
//     name: "إبراهيم",
//     gender: "ذكر",
//     age: 0,
//     alive: true,
//     img: "assets/إبراهيم عبد الله.jpg",
//   },
//   {
//     id: 12,
//     pid: 9,
//     name: "أحمد",
//     gender: "ذكر",
//     age: 0,
//     alive: true,
//     img: "assets/أحمد عبد الله.jpg",
//   },
//   {
//     id: 13,
//     pid: 4,
//     name: "مارية",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "assets/أحمد عبد الله.jpg",
//   },
//   {
//     id: 14,
//     pid: 9,
//     name: "خزامى",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "assets/أحمد عبد الله.jpg",
//   },
//   {
//     id: 15,
//     pid: 4,
//     name: "رغد",
//     gender: "أنثى",
//     age: 28,
//     alive: true,
//     // img: "assets/أحمد عبد الله.jpg",
//   },
//   {
//     id: 16,
//     pid: 9,
//     name: "بلقيس",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "assets/أحمد عبد الله.jpg",
//   },
//   {
//     id: 17,
//     pid: 4,
//     name: "حمزة",
//     gender: "ذكر",
//     age: 0,
//     alive: true,
//     img: "assets/حمزة عبد الله.jpg",
//   },
//   {
//     id: 18,
//     pid: 4,
//     name: "صفية",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "assets/حمزة عبد الله.jpg",
//   },
//   {
//     id: 19,
//     pid: 4,
//     name: "أريج",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "assets/حمزة عبد الله.jpg",
//   },
//   {
//     id: 20,
//     pid: 4,
//     name: "عمر",
//     gender: "ذكر",
//     age: 0,
//     alive: true,
//     img: "assets/عمر عبد الله.jpg",
//   },
//   {
//     id: 21,
//     pid: 4,
//     name: "عائشة",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     //   img: "assets/عمر عبد الله.jpg"
//   },
//   {
//     id: 22,
//     pid: 4,
//     name: "الزهراء",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "assets/عمر عبد الله.jpg",
//   },
//   {
//     id: 23,
//     pid: 4,
//     name: "خالد",
//     gender: "ذكر",
//     age: 0,
//     alive: true,
//     img: "assets/خالد عبد الله.jpg",
//   },
//   {
//     id: 24,
//     pid: 4,
//     name: "آسية",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "assets/عمر عبد الله.jpg",
//   },
//   {
//     id: 25,
//     pid: 7,
//     tags: ["assistant"],
//     name: "أسماء الكريدا",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "https://cdn.balkan.app/shared/9.jpg",
//   },
//   {
//     id: 26,
//     pid: 25,
//     name: "يارا",
//     gender: "أنثى",
//     age: 0,
//     alive: true,
//     // img: "assets/عمر عبد الله.jpg",
//   },
//   {
//     id: 27,
//     pid: 25,
//     name: "عبد الله",
//     gender: "ذكر",
//     age: 0,
//     alive: true,
//     img: "assets/عبد الله حمد.jpg",
//   },
// ];
